### PR TITLE
PE-5234: Running unit tests

### PR DESCRIPTION
**Pull request by hanpeter**
## What does this PR do?

This PR properly implements the unit tests for this library.

## Why is this change being made?

The existing unit tests were broken and were being skipped.

## How was this tested? How can the reviewer verify your testing?

The change was tested by running unit tests.

## Completion checklist

- [x] The pull request has been appropriately labeled according to
  our [conventions](https://kruxdigital.jira.com/wiki/display/EN/Changes+and+Peer+Review).
- [x] The version of the package has been updated according to [Semantic Versioning](http://semver.org/).
- [x] The change has unit & integration tests as appropriate.
- [x] Documentation is up to date and correct.
- [x] Dependencies are correctly listed under `Pipfile` and
      are up to date without going over a major version.
- [x] Stakeholders have been notified. Workflow-impacting changes have
      been appropriately socialized to avoid surprises.
- [x] The change is either small or have been canaried in the appropriate environment(s).

### CODE REVIEW

**Review by jnewman — APPROVED** [review]
Sweet

**Comment by jnewman** [comment]
Is it still WIP (looks fine)? (I'd call this a bugfix :-))

**Review by dllopis-sfdc — APPROVED** [review]
LGTM, though I’m pretty unfamiliar with SQS, and I’m not really evaluating the tests.

**Comment by hanpeter** [comment]
@jnewman, I thought I pressed the save button. No, it is no longer an WIP PR.

**Pull request merged**
