### PR TITLE
W-6690988: Migrate to Python 3

### PR DESCRIPTION
**Pull request by hanpeter**
## What does this PR do?

1. This PR updates the copyright dates.
1. This PR updates the code so that this library is Python 3 compatible.
1. This PR updates `setup.py` to be more like that of a library.

## Why is this change being made?

We want to migrate our Python repositories to Python 3.

## How was this tested? How can the reviewer verify your testing?

The change was tested manually on the local development environment.
```bash
$ nosetests
#4 Sqs.delete_messages() correctly deletes given messages ... ok
#15 Sqs.delete_messages() correctly does nothing for no messages ... ok
#12 Sqs.get_messages() correctly receives messages and converts them into dictionary ... ok
#14 Sqs.get_messages() correctly leaves the body as is when `is_json` is set to False ... ok
#13 Sqs.get_messages() correctly sends the parameters to Boto ... ok
#11 Sqs._get_queue() correctly uses the cached queue object ... ok
#10 Sqs._get_queue() correctly creates and caches the queue upon the first call ... ok
#16 Sqs._get_random_id() correctly generate a random string ... ok
#8 Sqs.__init__() correctly initialize internal fields ... ok
#9 Sqs.__init__() correctly raise an error for non-supported Boto objects ... ok
#20 Sqs.send_messages() correctly sends given messages ... ok
#21 Sqs.send_messages() correctly divides up messages in chunks ... ok
#22 Sqs.send_messages() correctly does nothing for no messages ... ok
#23 Sqs.send_messages() correctly sends given group ID if provided ... ok
#24 Sqs.send_messages() correctly errors upon invalid message type ... ok

Name                   Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------------------
krux_sqs/__init__.py       1      0      0      0   100%
krux_sqs/cli.py           20     10      2      1    50%   27-32, 36-38, 41, 48-50, 55, 54->55
krux_sqs/sqs.py           79     13     32      0    81%   47-66, 77-85
------------------------------------------------------------------
TOTAL                    100     23     34      1    76%
----------------------------------------------------------------------
Ran 15 tests in 1.601s

OK
$ krux-sqs-test
[]
$ python --version
Python 3.6.9
```

## What gif best describes this PR or how it makes you feel?

I can't think of a good one

## Completion checklist

- [x] The pull request has been appropriately labeled according to
  our [conventions](https://kruxdigital.jira.com/wiki/display/EN/Changes+and+Peer+Review).
- [x] The version of the package has been updated according to [Semantic Versioning](http://semver.org/).
- [x] The change has unit & integration tests as appropriate.
- [x] Documentation is up to date and correct.
- [x] Dependencies are correctly listed under `Pipfile` and
      are up to date without going over a major version.
- [x] Stakeholders have been notified. Workflow-impacting changes have
      been appropriately socialized to avoid surprises.
- [x] The change is either small or have been canaried in the appropriate environment(s).

### CODE REVIEW

**Comment by hanpeter** [comment]
retest this please

**Comment by hanpeter** [comment]
retest this please

**Comment by hanpeter** [comment]
retest this please

**Comment by hanpeter** [comment]
retest this please

**Review by paul-krohn — APPROVED** [review]

**Review by dllopis-sfdc — APPROVED** [review]

**Pull request merged**
